### PR TITLE
Fixup deprecated ModulesApp method in SquirrelApp

### PR DESCRIPTION
**Pull request by cticenhour**
This fixes up a deprecated method that is affecting Zapdos. Tagging @smpark7 for review. Thanks!

### CODE REVIEW

**Review by smpark7 — APPROVED** [review]
Thanks for making these changes! LGTM

**Comment by smpark7** [comment]
I'll merge in a minute after I compile and test the changes. I noticed there's no continuous tests in this repo.

**Comment by cticenhour** [comment]
If desired, CIVET CI could be set up for Squirrel. Though with the infrequency of updates at this level, and the testing done in Zapdos and Moltres....maybe not?

**Comment by cticenhour** [comment]
Happy to do so if you wanted it.

**Comment by smpark7** [comment]
Yea, given your points and the simplicity of squirrel's kernels, I don't think squirrel needs its own CI setup.

**Pull request merged**
